name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        push: true
        dockerfile: ./docker/Dockerfile
        tags: heksahiti/lineten-test:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set permissions for private key
      run: |
        chmod 400 ./terraform/ec2/key-pair
    - name: Pull Docker image
      env:
        HOSTNAME: ${{ secrets.REMOTE_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ./terraform/ec2/key-pair ubuntu@${HOSTNAME} 'sudo docker pull heksahiti/lineten-test:latest'
    - name: Stop running container
      env:
          HOSTNAME: ${{ secrets.REMOTE_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ./terraform/ec2/key-pair ubuntu@${HOSTNAME} 'sudo docker stop hello-lineten || true'
        ssh -o StrictHostKeyChecking=no -i ./terraform/ec2/key-pair ubuntu@${HOSTNAME} 'sudo docker rm hello-lineten || true'
    - name: Run new container
      env:
        HOSTNAME: ${{ secrets.REMOTE_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ./terraform/ec2/key-pair ubuntu@${HOSTNAME} 'sudo docker run -d --name hello-lineten -p 80:5500 heksahiti/lineten-test:latest'
